PK-iMac-2:chromatiq Koncar$ git init Initialized empty Git repository in /Users/Koncar/gh/chromatiq/.git/ PK-iMac-2:chromatiq Koncar$ git commit -m "first commit" On branch master
Initial commit

Untracked files:
	PlayFromWebCam.cs

nothing added to commit but untracked files present
PK-iMac-2:chromatiq Koncar$ git remote add origin https://github.com/Glyphed/chromatiq.git
PK-iMac-2:chromatiq Koncar$ git push -u origin master
Username for 'https://github.com': glyphed
Password for 'https://glyphed@github.com':
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/Glyphed/chromatiq.git'
PK-iMac-2:chromatiq Koncar$ git push -all
error: did you mean `--all` (with two dashes ?)
PK-iMac-2:chromatiq Koncar$ git push --all
No refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
Everything up-to-date
PK-iMac-2:chromatiq Koncar$ got push help
-bash: got: command not found
PK-iMac-2:chromatiq Koncar$ git push help
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: 'help' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
PK-iMac-2:chromatiq Koncar$ git commit PlayFromWebCam.cs
error: pathspec 'PlayFromWebCam.cs' did not match any file(s) known to git.
PK-iMac-2:chromatiq Koncar$ dir
-bash: dir: command not found
PK-iMac-2:chromatiq Koncar$ help
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin14)
These shell commands are defined internally.  Type `help' to see this list.
Type `help name' to find out more about the function `name'.
Use `info bash' to find out more about the shell in general.
Use `man -k' or `info' to find out more about commands not in this list.

A star (*) next to a name means that the command is disabled.

 JOB_SPEC [&]                       (( expression ))
 . filename [arguments]             :
 [ arg... ]                         [[ expression ]]
 alias [-p] [name[=value] ... ]     bg [job_spec ...]
 bind [-lpvsPVS] [-m keymap] [-f fi break [n]
 builtin [shell-builtin [arg ...]]  caller [EXPR]
 case WORD in [PATTERN [| PATTERN]. cd [-L|-P] [dir]
 command [-pVv] command [arg ...]   compgen [-abcdefgjksuv] [-o option
 complete [-abcdefgjksuv] [-pr] [-o continue [n]
 declare [-afFirtx] [-p] [name[=val dirs [-clpv] [+N] [-N]
 disown [-h] [-ar] [jobspec ...]    echo [-neE] [arg ...]
 enable [-pnds] [-a] [-f filename]  eval [arg ...]
 exec [-cl] [-a name] file [redirec exit [n]
 export [-nf] [name[=value] ...] or false
 fc [-e ename] [-nlr] [first] [last fg [job_spec]
 for NAME [in WORDS ... ;] do COMMA for (( exp1; exp2; exp3 )); do COM
 function NAME { COMMANDS ; } or NA getopts optstring name [arg]
 hash [-lr] [-p pathname] [-dt] [na help [-s] [pattern ...]
 history [-c] [-d offset] [n] or hi if COMMANDS; then COMMANDS; [ elif
 jobs [-lnprs] [jobspec ...] or job kill [-s sigspec | -n signum | -si
 let arg [arg ...]                  local name[=value] ...
 logout                             popd [+N | -N] [-n]
 printf [-v var] format [arguments] pushd [dir | +N | -N] [-n]
 pwd [-LP]                          read [-ers] [-u fd] [-t timeout] [
 readonly [-af] [name[=value] ...]  return [n]
 select NAME [in WORDS ... ;] do CO set [--abefhkmnptuvxBCHP] [-o opti
 shift [n]                          shopt [-pqsu] [-o long-option] opt
 source filename [arguments]        suspend [-f]
 test [expr]                        time [-p] PIPELINE
 times                              trap [-lp] [arg signal_spec ...]
 true                               type [-afptP] name [name ...]
 typeset [-afFirtx] [-p] name[=valu ulimit [-SHacdfilmnpqstuvx] [limit
 umask [-p] [-S] [mode]             unalias [-a] name [name ...]
 unset [-f] [-v] [name ...]         until COMMANDS; do COMMANDS; done
 variables - Some variable names an wait [n]
 while COMMANDS; do COMMANDS; done  { COMMANDS ; }
PK-iMac-2:chromatiq Koncar$ ls
PlayFromWebCam.cs
PK-iMac-2:chromatiq Koncar$ git commit PlayFromWebCam.cs
error: pathspec 'PlayFromWebCam.cs' did not match any file(s) known to git.
PK-iMac-2:chromatiq Koncar$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	PlayFromWebCam.cs

nothing added to commit but untracked files present (use "git add" to track)
PK-iMac-2:chromatiq Koncar$ git add PlayFromWebCam.cs
PK-iMac-2:chromatiq Koncar$ git commit PlayFromWebCam.cs
Aborting commit due to empty commit message.
PK-iMac-2:chromatiq Koncar$ git commit PlayFromWebCam.cs

~
~
~
~
~
~
~
~
~